fixed buttons and font size
aldaitzwild/WCS_Pull_Request_Tracker pull request #29
Opened 2023-06-07 07:56 UTC by AxelR972

2023-06-07 08:02 UTC, Dldvlpr approved these changes, later dismissed

2023-06-07 09:03 UTC, aldaitzwild requested changes
Conflict with dev

2023-06-08 09:50 UTC, aldaitzwild requested changes

2023-06-08 09:50 UTC, aldaitzwild commented on templates/project/show.html.twig
> +        <div class="container">
This a weird implementation of the bootstrap hierarchy

2023-06-08 09:50 UTC, aldaitzwild commented on templates/project/show.html.twig
> +{% endblock %}
No ! This page doesn't work

2023-06-08 13:16 UTC, aldaitzwild approved these changes

2023-06-08 14:41 UTC, zakaria6907 approved these changes

2023-06-09 06:54 UTC, merged