add PullRequestController
aldaitzwild/WCS_Pull_Request_Tracker pull request #34
Opened 2023-06-07 13:32 UTC by AxelR972

partial PR for the PullRequestController and this function show

2023-06-07 13:34 UTC, zakaria6907 approved these changes, later dismissed

2023-06-08 09:18 UTC, Dldvlpr requested changes

2023-06-08 09:18 UTC, Dldvlpr commented on src/Controller/PullRequestController.php
> +    #[Route('/pull/request', name: 'app_pull_request')]
this road name is different from that of line 20.
/pull/request and /pullRequest

they should have the same structure.

2023-06-08 09:18 UTC, Dldvlpr commented on templates/pull_request/index.html.twig
> +{% endblock %}
It's generated code but we don't need it

2023-06-08 09:18 UTC, Dldvlpr commented on templates/pull_request/show.html.twig
empty file ?

2023-06-08 09:31 UTC, AxelR972 reviewed
partial PR

2023-06-08 12:17 UTC, aldaitzwild approved these changes

2023-06-08 12:17 UTC, merged