S 01 30 authentification standard pour les users
aldaitzwild/WCS_Pull_Request_Tracker pull request #35
Opened 2023-06-08 09:13 UTC by Dldvlpr

FEAT!:
- Add Service folder and UserAthenticator
- Add Security Controller
- Add logout link
- path: '/' are now the homepage
- added security on the controllers to be accessible only to people with the 'ROLE_USER"

2023-06-08 09:42 UTC, AxelR972 approved these changes, later dismissed

2023-06-08 10:04 UTC, aldaitzwild requested changes

2023-06-08 10:04 UTC, aldaitzwild commented on assets/scripts/ajaxModalSearch.js
> +console.log(projectId);
Dead code !

2023-06-08 12:20 UTC, aldaitzwild approved these changes, later dismissed

2023-06-08 13:15 UTC, AxelR972 submitted a review, later dismissed

2023-06-09 07:09 UTC, AxelR972 approved these changes

2023-06-09 07:18 UTC, AxelR972 approved these changes

2023-06-09 07:27 UTC, zakaria6907 approved these changes

2023-06-09 07:40 UTC, aldaitzwild approved these changes

2023-06-09 07:40 UTC, merged