general style fixed
aldaitzwild/WCS_Pull_Request_Tracker pull request #46
Opened 2023-06-14 14:21 UTC by AxelR972

fixed font size, style of the buttons and added the icon green/red for the view of the status

2023-06-14 14:23 UTC, zakaria6907 approved these changes, later dismissed

2023-06-14 15:17 UTC, aldaitzwild requested changes

2023-06-14 15:17 UTC, aldaitzwild commented on templates/contributor/index.html.twig
> +		<div class="container">
Why does your container is in a row here ?

2023-06-15 08:20 UTC, aldaitzwild approved these changes

2023-06-15 08:22 UTC, zakaria6907 approved these changes

2023-06-15 08:32 UTC, merged