33 service de synchronisation des pr pour alimentation en base
aldaitzwild/WCS_Pull_Request_Tracker pull request #52
Opened 2023-06-15 18:29 UTC by Dldvlpr

FEAT!:

added method to retrieve all pr

added a method to check if the existing pr in db exists on github

addition of a method to add the pr which are not present in db

modification of the front with clickable links from projects to pr

possibility of having a nullabe user for pr to identify accounts not yet registered

2023-06-15 21:40 UTC, zakaria6907 approved these changes, later dismissed

2023-06-19 07:42 UTC, aldaitzwild requested changes

2023-06-19 07:42 UTC, aldaitzwild commented on src/Controller/SecurityController.php
> +use App\Repository\UserRepository;
Useless "use"

2023-06-19 15:51 UTC, Dldvlpr commented on src/Controller/SecurityController.php
> +use App\Repository\UserRepository;
remove

2023-06-19 20:16 UTC, zakaria6907 submitted a review, later dismissed

2023-06-20 10:27 UTC, AxelR972 approved these changes, later dismissed

2023-06-21 10:18 UTC, aldaitzwild requested changes

2023-06-21 10:18 UTC, aldaitzwild commented on src/Controller/SecurityController.php
> +use App\Repository\UserRepository;
Useless "use"

2023-06-26 08:18 UTC, AxelR972 approved these changes

2023-06-26 08:29 UTC, zakaria6907 approved these changes

2023-06-26 10:27 UTC, aldaitzwild approved these changes

2023-06-26 10:27 UTC, merged