S2 50 style de la vue des pr
aldaitzwild/WCS_Pull_Request_Tracker pull request #56
Opened 2023-06-20 11:28 UTC by AxelR972

change the SCSS for the font and fixed the PR status now a PR merged are closed and a PR not merged are open

2023-06-20 11:44 UTC, zakaria6907 approved these changes, later dismissed

2023-06-21 10:21 UTC, aldaitzwild requested changes

2023-06-21 10:21 UTC, aldaitzwild commented on assets/scripts/tooltip.js
> +});
Jquery is forbidden ... and probably doesn't work ...

2023-06-21 13:33 UTC, AxelR972 commented on src/Repository/PullRequestRepository.php
Add the function for order the status by Open first

2023-06-21 14:38 UTC, aldaitzwild approved these changes

2023-06-21 14:40 UTC, zakaria6907 approved these changes

2023-06-21 14:49 UTC, merged