S3-réorganiser la page détaillé d'un contributeur
aldaitzwild/WCS_Pull_Request_Tracker pull request #59
Opened 2023-06-21 14:35 UTC by zakaria6907

-reorganize a contributor's page .
-reorganize contributor list page .
-fix the problem that a pr can be merged with an open status

2023-06-21 15:43 UTC, AxelR972 requested changes

2023-06-21 15:43 UTC, AxelR972 commented on src/Controller/ProjectController.php
> +        $contributors = $contributorRepository->getContributorsInProjectByOrderAlph($project);
What is Order Alph ?

2023-06-22 08:50 UTC, AxelR972 approved these changes, later dismissed

2023-06-23 07:24 UTC, AxelR972 approved these changes

2023-06-23 07:27 UTC, aldaitzwild approved these changes

2023-06-23 07:27 UTC, merged