find all contributors for project
aldaitzwild/WCS_Pull_Request_Tracker pull request #72
Opened 2023-07-04 10:15 UTC by zakaria6907

- add a fullName field
- retrieve all contributors associated with projects

2023-07-04 12:02 UTC, AxelR972 submitted a review, later dismissed

2023-07-04 12:36 UTC, aldaitzwild requested changes

2023-07-04 12:36 UTC, aldaitzwild commented on src/Repository/ContributorRepository.php
> +                $this->projectRepository->save($project, true);
Why do you do this ? Use addProject in Contributor instead.

2023-07-04 13:55 UTC, aldaitzwild requested changes

2023-07-04 13:55 UTC, aldaitzwild commented on src/Repository/ContributorRepository.php
> +                $this->save($contributor, true);
Why have you two $this->save() ? you only should have one to not make two request

2023-07-05 09:40 UTC, aldaitzwild submitted a review, later dismissed

2023-07-05 09:54 UTC, AxelR972 submitted a review, later dismissed

2023-07-05 14:47 UTC, AxelR972 approved these changes

2023-07-05 14:51 UTC, aldaitzwild approved these changes

2023-07-05 14:51 UTC, merged