fix add a project
aldaitzwild/WCS_Pull_Request_Tracker pull request #81
Opened 2023-07-10 14:22 UTC by zakaria6907

2023-07-12 13:39 UTC, AxelR972 approved these changes, later dismissed

2023-07-12 14:36 UTC, aldaitzwild requested changes

2023-07-12 14:36 UTC, aldaitzwild commented on src/Entity/Project.php
> +        $this->fullName = substr($githubLink, strrpos($githubLink, '.com/') + 5);
Not the right place to call this

2023-07-12 17:59 UTC, AxelR972 submitted a review, later dismissed

2023-07-13 07:08 UTC, AxelR972 approved these changes

2023-07-13 07:39 UTC, aldaitzwild approved these changes

2023-07-13 07:39 UTC, merged